@startuml
!include <archimate/Archimate>
' https://github.com/awslabs/aws-icons-for-plantuml/blob/main/source/AWSCommon.puml
!include <awslib/AWSCommon>

' Splits at the ~ character and iterates over each item
!foreach $item in %splitstr('General~SecurityIdentityCompliance~NetworkingContentDelivery~DeveloperTools~Database~Storage~ApplicationIntegration~Compute~Groups~MediaServices~MachineLearning', '~')
    ' https://github.com/plantuml/plantuml-stdlib/tree/master/stdlib/awslib20
    !include <awslib/$item/all.puml>
!endfor
hide stereotype
skinparam linetype ortho
left header AWS Diagram

AWSCloudGroup(cloud) {
    VPCGroup(vpc) {
        VPCInternetGateway(internet_gateway, "Internet gateway", "")
        AvailabilityZoneGroup(az_1, "\tAvailability Zone 1\t") {
        PublicSubnetGroup(az_1_public, "Public subnet") {
            VPCNATGateway(az_1_nat_gateway, "NAT gateway", "") #Transparent
        }
        PrivateSubnetGroup(az_1_private, "Private subnet") {
            EC2Instance(az_1_ec2_1, "Instance", "") #Transparent
        }
        Rel_Serving_Up(az_1_ec2_1, az_1_nat_gateway, '')
    }
    AvailabilityZoneGroup(az_2, "\tAvailability Zone 2") {
        PublicSubnetGroup(az_2_public, "Public subnet") {
            VPCNATGateway(az_2_nat_gateway, "NAT gateway", "") #Transparent
        }
        PrivateSubnetGroup(az_2_private, "Private subnet") {
            EC2Instance(az_2_ec2_1, "Instance", "") #Transparent
        }
        Rel_Serving_Up(az_2_ec2_1, az_2_nat_gateway, '')
    }
  }
}
@enduml