@startuml
'!include_once https://raw.githubusercontent.com/imochoa/dotfiles/master/dotfiles/plantuml/plantuml_style.iuml
!include_once style.iuml

skinparam arrowColor Black

' Pipeline colors
!color_rgb = "PaleGreen"

' Arrow colors
' !$preproc_rgb = "DarkGoldenRod"

' PROCEDURES
!procedure $json($txt, $name)
file "$txt" <<JSON>> as $name #RoyalBlue;line:Black;text:White
!endprocedure

@enduml