#!/usr/bin/env -S uv run --script

# /// script
# requires-python = ">=3.12"
# dependencies = [
#   "sh",
#   "typer",
#   "pdbpp",
#   ]
# ///

import logging
import os
from enum import StrEnum
import pdbpp
import pathlib
import sh
import typer
from sh import tar, sha256sum, grep

logging.basicConfig(level=logging.INFO)

NUM_CORES = min(4, os.cpu_count())


def main(name: str):
    print(f"Hello {name}")

if __name__ == "__main__":
    main(name="World")

# vim: ft=python
