@startuml

' !include style.iuml
<style file=hoho.css>

' <style file="/Users/imochoa/Code/cookiecutter-plantuml/{{cookiecutter.name}}/internals/hoho.css">
' <style file=https://hostname/some-path/v1/plantuml-style.css>
 

' printed in blue
actor Bob
' this will now be printed in Red
actor Sally <<myStyle>>
@enduml